services:
  # Backend Service
  - type: web
    name: mi-app-ventas-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install && npm run build
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000

  # Frontend Service
  - type: web
    name: mi-app-ventas-frontend
    env: static
    buildCommand: npm ci && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_API_URL
        value: https://mi-app-ventas-backend.onrender.com
